Add new authenticator required action (#16)
* Fix 'NoClassDefFoundError: org/apache/logging/log4j/util/Lazy' error

* Fix 'HTTP 405 Method Not Allowed' error when calling the REST endpoint

* Add JUnit test for event listener

* Add resources

* Edit JUnit-test to extract expected successfull login time from access-token instead of logs

* Remove unnecessary environment variable configuration

* Refactor JUnit test: Extract  from access-token without adding new external dependencies.

* Remove unnecessary dependency

* Refactor: Change access modifiers of methods to private

* Refactor JUnit test: Remove duplicate method

* Rename test files to *IT.java and configure Maven Failsafe plugin

* Fixing open conversations on PR, refactored MAVEN-Plugins

* WiP added a functional Authenticator without any testing. Tests will be added next

* WiP added UI testing for Terms and condition

* Added UI_Tests to check functionality for required action authenticator

* change package to verify

* add steps for playwright tests

* add steps for playwright tests #2

* added documentation

* fix missing dash

* add one more header

* fixing comments

* WiP added check for empty AuthenticatorConfig

* WiP added check for empty AuthenticatorConfig #2 added TODO to test

* WiP added check for empty AuthenticatorConfig #2 added TODO to test

* Resolved all comments

---------

Co-authored-by: Hassan El Mailoudi <hassan.elmailoudi@conciso.de>