Fix errors/add tests (#4)
* Fix 'NoClassDefFoundError: org/apache/logging/log4j/util/Lazy' error

* Fix 'HTTP 405 Method Not Allowed' error when calling the REST endpoint

* Add JUnit test for event listener

* Add resources

* Edit JUnit-test to extract expected successfull login time from access-token instead of logs

* Remove unnecessary environment variable configuration

* Refactor JUnit test: Extract  from access-token without adding new external dependencies.

* Remove unnecessary dependency

* Refactor: Change access modifiers of methods to private

* Refactor JUnit test: Remove duplicate method

* Rename test files to *IT.java and configure Maven Failsafe plugin

* Fixing open conversations on PR, refactored MAVEN-Plugins

---------

Co-authored-by: Hassan El Mailoudi <hassan.elmailoudi@conciso.de>
Co-authored-by: Robin Meese <39960884+robson90@users.noreply.github.com>